"""Render or validate the generated CLI reference from the live argparse tree."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "python"
if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))

from prolog_tsetlin.cli import _parser  # noqa: E402

OUTPUT = ROOT / "docs" / "manual" / "reference" / "cli.md"


def _format_action(action) -> str:
    flags = ", ".join(action.option_strings) if action.option_strings else action.dest
    metavar = f" {action.metavar}" if action.metavar else ""
    help_text = f" — {action.help}" if action.help and action.help != "==SUPPRESS==" else ""
    default = ""
    if action.default not in (None, "==SUPPRESS==") and not action.option_strings == []:
        # Show defaults for optional arguments where meaningful
        if not isinstance(action.default, bool) or action.default:
            if action.default != [] and action.default != "":
                default = f" (default: `{action.default!r}`)"
    required = " (required)" if getattr(action, "required", False) else ""
    choices = f" {{choices: {', '.join(map(str, action.choices))}}}" if getattr(action, "choices", None) else ""
    return f"| `{flags}{metavar}` | {help_text.strip(' — ')}{choices}{default}{required} |"


def _render_parser(parser, prefix: str = "ptm") -> list[str]:
    import argparse

    lines: list[str] = []
    # Heading
    heading = prefix
    level = prefix.count(" ") + 2  # ptm -> ##, ptm artifact -> ###, etc.
    lines.append(f"{'#' * level} `{heading}`")
    lines.append("")
    if parser.description:
        lines.append(parser.description)
        lines.append("")
    if parser.epilog:
        lines.append(f"*{parser.epilog}*")
        lines.append("")
    # Arguments (excluding subparsers helper)
    actions = [a for a in parser._actions if a.dest not in ("help", "==SUPPRESS==")]
    # Separate positional and optional for readability
    optionals = [a for a in actions if a.option_strings]
    positionals = [a for a in actions if not a.option_strings]
    # Filter out subparsers actions from table
    def is_subparsers(a) -> bool:
        return isinstance(a, argparse._SubParsersAction)

    table_actions = [a for a in positionals + optionals if not is_subparsers(a)]
    if table_actions:
        lines.append("| Argument | Help |")
        lines.append("|---|---|")
        for action in table_actions:
            lines.append(_format_action(action))
        lines.append("")
    # Subcommands: find subparsers actions
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            choices = action.choices or {}
            lines.append(f"Subcommands of `{prefix}`:")
            lines.append("")
            for name, sub in sorted(choices.items()):
                # Help for this subcommand is stored in the choices entry's help via _choices_actions
                # Retrieve from the action's _choices_actions
                help_text = ""
                for choice_action in getattr(action, "_choices_actions", []):
                    if choice_action.dest == name or getattr(choice_action, "help", None):
                        # argparse stores help on the _choice_action
                        if choice_action.dest == name:
                            help_text = choice_action.help or ""
                            break
                # fallback: sub.description first line
                if not help_text:
                    help_text = (getattr(sub, "description", "") or "").split("\n")[0]
                lines.append(f"- `{prefix} {name}` — {help_text}")
            lines.append("")
            for name, sub in sorted(choices.items()):
                lines.extend(_render_parser(sub, f"{prefix} {name}"))
    return lines


def render_cli_reference() -> str:
    parser = _parser()
    header = [
        "<!-- Generated by scripts/render_cli_reference.py; do not edit directly. -->",
        "# CLI reference",
        "",
        "> The `argparse` tree in `python/prolog_tsetlin/cli.py` owns command names, arguments, defaults, metavariables, and syntax. This page is generated from the live parser; `ptm help <topic>` and `docs/manual/reference/help-topics.md` share the conceptual topic registry.",
        "",
        "```bash",
        "ptm --help",
        "ptm help <topic>",
        "ptm artifact --help",
        "ptm search --help",
        "```",
        "",
        "Man pages `ptm(1)` and `ptmrt(1)` are produced from the same source via the Sphinx `man` builder (`man_pages` in `docs/conf.py`).",
        "",
    ]
    body = _render_parser(parser)
    footer = [
        "See [Help topics](help-topics.md) for conceptual topics, examples, requirements, and workbench controls.",
        "",
    ]
    return "\n".join(header + body + footer)


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail instead of updating when stale")
    args = parser.parse_args()
    expected = render_cli_reference()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None
    if args.check:
        if current != expected:
            raise SystemExit(f"generated CLI reference is stale: run {Path(__file__).name}")
        print(f"generated CLI reference: {OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated CLI reference: wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
